### ISSUE TITLE
character (innovation chris)  require from data/2002um.cns , crash at fight screen

### ISSUE THREAD

**Issue by Xenorz** [Windblade-GR01/Ikemen-GO#260] opened 2021-05-15 05:32 UTC
.\external\script\start.lua:1351: data/2002um.cns:1883:
Command doesn't exist: recovery
stack traceback:
	[G]: in function 'game'
	.\external\script\start.lua:1351: in function 'f_game'
	.\external\script\start.lua:1728: in function 'launchFight'
	external/script/default.lua:2: in function <external/script/default.lua:0>
	.\external\script\start.lua:1410: in function 'f'
	external/script/main.lua:2932: in function 'loop'
	external/script/main.lua:2996: in function 'loop'
	external/script/main.lua:3870: in main chunk
	[G]: ?

**Comment by K4thos** [comment] 2021-06-04 16:02
can't reproduce it with following versions:
https://mugenarchive.com/forums/downloads.php?do=file&id=65623-innovation-chris-ahuron-xs-and-gua
https://mugenarchive.com/forums/downloads.php?do=file&id=78835-innovation-chris-ahuron-xs-and-gua-phoenix
Next time please upload problematic character so that we don't have to search for it all over the internet.

I assume he used old ikemen go build that had problems like this (fixed in 0.96), so ticket should be closed.

**Closed** 2021-06-06 19:29 UTC
Labels: bug
