### ISSUE TITLE
Mobile?

### ISSUE THREAD

**Issue by Trey336** [Windblade-GR01/Ikemen-GO#343] opened 2021-08-28 22:20 UTC
Is making a mobile port possible? I mean, atleast I asked, but if it is impossible, I'm sorry for wasting everyone's precious time, ikemen on the go would be awesome. Has anyone tried to do this? 🤔

**Comment by Adnan1091** [comment] 2021-08-29 12:35
This was asked several times(including me).The author says GLFW doesn't have mobile support,but i saw it was discussed in GLFW's github page and a fork that supports android is avilable as far as i know.

**Comment by xx1182** [comment] 2021-08-30 13:40
If you really, really want... and don't mind being autistic:
You can use Termux setup a VNCServer and boom, it works.

First you gotta compile tho.

Regards.

**Comment by XTRAXTREME** [comment] 2021-09-06 15:08
Someone explain me this

**Comment by xx1182** [comment] 2021-09-06 16:10
> Someone explain me this
Sure, let's exchange addresses, or do it in videocall, is a bit complicated depending on your expertise in programming and troubleshooting, because it inquires:
Setting up an environment to compile your binary


> Someone explain me this
Sure but then you write a wiki article

**Comment by DJPilouDevelopersandmore** [comment] 2021-09-24 02:42
i do this ported by android and ios mobile

**Comment by Orochikyocr** [comment] 2021-11-07 21:19
This should be closed, because tbh, once Gacel feels the engine is ready to go Android, he will not hesitate and it has been asked so many times.

**Comment by Windblade-GR01** [comment] 2021-11-08 22:02
Closing because is a duplicate of #224.

**Closed by Windblade-GR01** 2021-11-08 22:02 UTC
Labels: duplicate, enhancement
