### ISSUE TITLE
[FEATURE REQUEST] Implement video player for intro and end scenes.

### ISSUE THREAD

**Issue by shurato** [Windblade-GR01/Ikemen-GO#355] opened 2021-09-22 20:32 UTC
Please try to implement a video player so we can make high quality and lightweight intros,
I suggest using the video format, WEBM, which is well compressed, the openbor engine already uses videos in this format.

**Comment by Windblade-GR01** [comment] 2021-11-08 21:52
This is a duplicate of #193.

**Closed by Windblade-GR01** 2021-11-08 21:52 UTC
Labels: duplicate
