### ISSUE TITLE
Inconsistency with 2-button commands (multiple-button input window very tight?)

### ISSUE THREAD

**Issue by VinVulpis** [Windblade-GR01/Ikemen-GO#368] opened 2021-10-17 20:00 UTC
So, something else I've noticed while working out all of the kinks with control issues I had between the two engines, I noticed that it seems like 2 button commands are either inconsistent, or the frame window for both to be pressed is much tighter in Ikemen Go compared to Mugen?

In play testing and messing around I'm noticing that I'm dropping my combos a lot in Ikemen Go where I intend to use the super super commands I gave my characters, which all use 2-button inputs. They often do not activate, and I get a 1 button command instead (or nothing if the character does not have an equivalent 1 button move) I've tried messing with the time and buffer.time values to see if there's any difference and there doesn't seem to be. It just feels like the Ikemen window to press more than 1 button is much tighter.

Video of both engines played at the same time.
https://user-images.githubusercontent.com/66293146/137643320-a9a5cd2e-dbbc-4fa7-9050-2cd820ab2253.mp4

If nothing else, an option to widen multi-button input timing in engine would be nice.
Thanks much!

**Comment by randomarcadedude** [comment] 2021-10-19 21:21
This has been happening to me with every version of Ikemen Go. The only thing that works consistently is doing the moves as part of a combo, which I'm guessing has something to do with the inputs being buffered and not necessarily detected at the same time.

**Comment by Orochikyocr** [comment] 2021-11-08 18:52
https://github.com/Windblade-GR01/Ikemen-GO/issues/264
This has been discussed extensively in the discord and devs are aware of it. They promised a new input parser for future releases.
Meanwhile, many people are just using input buffers.

**Comment by VinVulpis** [comment] 2021-11-08 19:15
> #264 This has been discussed extensively in the discord and devs are aware of it. They promised a new input parser for future releases. Meanwhile, many people are just using input buffers.

I actually use buffer times and I have a variable system I use for buffers between certain actions, and that's actually one way I confirmed it's just seemingly ignoring my 2-button inputs. The stateno that should show up for that variable in the clipboard just don't come up, but in a very inconsistent way that's hard to pin point, other than it usually happens in longer combos, and less-so when it's done raw.

**Comment by Windblade-GR01** [comment] 2021-11-08 21:43
This issue can count as a duplicate of #264.
So I'm gonna close it.

If you wanna add any info about this use the issue linked above.

**Closed by Windblade-GR01** 2021-11-08 21:43 UTC
